// FactTest generated host membrane (BOOTSTRAP-CONTRACTS C13; BOOTSTRAP-ARCHITECTURE section 9).
// Operations: DISCOVER, REQUEST, OPERATE, OBSERVE, RELEASE.  Result classes are normalized.
// This file is generated by factc-codegen from the VerifiedStrategy; every adapter below is one the
// verifier admitted.  Adding an adapter here without a verified variant fails the BundleVerifier.
export const Result = Object.freeze({
  OK: 'OK', UNAVAILABLE: 'UNAVAILABLE', DENIED: 'DENIED', POLICY_BLOCKED: 'POLICY_BLOCKED',
  UNSUPPORTED: 'UNSUPPORTED', LOST: 'LOST', RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  INVALID: 'INVALID', INTERNAL_FAILURE: 'INTERNAL_FAILURE',
});
export const adapters = {};
export function probePattern(n) { const p = new Uint8Array(n); for (let i = 0; i < n; i++) p[i] = (i * 37 + 11) & 0xff; return p; }
export function bytesEqual(a, b) { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false; return true; }
export async function sha256hex(bytes) {
  const d = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(d)].map(x => x.toString(16).padStart(2, '0')).join('');
}
