[workspace]
resolver = "2"
members = [
    "factory",
    "compiler/foundation",
    "compiler/source",
    "compiler/semantic",
    "compiler/capability",
    "compiler/implementation",
    "compiler/kernel",
    "compiler/wasm-abi",
    "host/factc",
]
default-members = [
    "factory",
    "compiler/foundation",
    "compiler/source",
    "compiler/semantic",
    "compiler/capability",
    "compiler/implementation",
    "compiler/kernel",
    "host/factc",
]
exclude = [
    "fixtures",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
publish = false

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
